### ISSUE TITLE
Key derivation support

### ISSUE THREAD

**Issue by graynk** [clausecker/freefare#4]
I'm looking at [this](https://github.com/nfc-tools/libfreefare/blob/master/examples/mifare-ultralightc-diversify.c) example of libfreefare and I can't find any function for `mifare_ultralightc_set_key` in `UltralightTag`, nor is there a `MifareKeyDeriver`. Are there any plans to add the support for this?
Here's the [commit](https://github.com/nfc-tools/libfreefare/commit/9d88c18833450a91b97fc6ac91c1d983ed3a8681) with most of the changes.

**Comment by clausecker** [comment]
This function is not part of any libfreefare release.  In fact, they haven't made a release since 0.4.0 which is the release this library has been written against.  If you can convince the library maintainers to perhaps make a new release, I can start adding the new features to the library.

**Comment by clausecker** [comment]
Addressed by PR #8 I believe.  @graynk, can you confirm?

**Comment by graynk** [comment]
That is correct, this PR adds a wrapper on `MifareKeyDeriver` and adds needed functions to `UltralightTag`

**Comment by clausecker** [comment]
I think we can close this then.
