### ISSUE TITLE
ReadPage returns zeroed array in ultralight.go

### ISSUE THREAD

**Issue by graynk** [clausecker/freefare#6]
https://github.com/fuzxxl/freefare/blob/0db9bd4463f361189042156563572f0517fa7b9c/0.3/freefare/ultralight.go#L63-L68

It should be `return data, nil` here. I could keep track of any issues that may arise as I work my way through my project that uses this wrapper, and then make a PR with all the fixes I end up with, so as not to spam with any more issues, if that's okay with you.

**Comment by clausecker** [comment]
Thank you for reporting this issue!  Making one huge pull request is probably a good idea.  I do not really work on this project anymore, but I'm happy to accept reasonable pull requests.

**Comment by clausecker** [comment]
Did you end up finishing your project?  If yes, I would definitely still appreciate a pull request.

**Comment by graynk** [comment]
It kind of got stuck in the middle because management didn't know if they wanted to use ultralight tags or not and then I changed workplaces, so I don't actually work with hardware anymore. But I did end up fixing a few bugs and used pretty much all of Ultralight's functionality in my prototype complete with key derivation, so I will try to dig it up and make a PR over the weekend!

**Comment by clausecker** [comment]
Thanks a lot!  Your help is very valuable.
